version: '3'
services:
  cache:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database